### PR TITLE
add CockroachDB auth plugin

### PR DESCRIPTION
**Pull request by cmnstmntmn**
- all credits goes to @knz
- tests should be reviewed

### CODE REVIEW

**Comment by ioolkos** [comment]
@cmnstmntmn, @knz cool stuff, thanks! :)

**Comment by dergraf** [comment]
@cmnstmntmn had a very quick look at the Lua code... one question is it basically the Postgres code but using SHA hashes instead of the PG crypto stuff?

**Comment by cmnstmntmn** [comment]
@dergraf, indeed

**Comment by dergraf** [comment]
While this could be merged that way, I'd prefer a more generic solution where we could e.g. change the hashing/password mechanism, this could be useful for the other database plugins as well, especially those that currently live with the potential bcrypt bottleneck... @larshesel any thoughts on this?

**Comment by larshesel** [comment]
I think that sounds like a good approach.

**Comment by larshesel** [comment]
As we'd rather have a generic approach I'll close this for now.

**Pull request closed without merging**
