### PR TITLE
Pass the path as proplist when starting a user plugin

### PR DESCRIPTION
**Pull request by rbino**
This is needed after bcad8893bf5ebdfa08eb16cfaaeaa72eae148bf9

### CODE REVIEW

**Comment by larshesel** [comment]
Could I get you to add a line to the changelog.md file mentioning the fix?

**Comment by rbino** [comment]
Done

**Comment by rbino** [comment]
I'm not sure why the CI fails

**Comment by larshesel** [comment]
We have some tests which are less deterministic than we'd want so sometimes they fail - something to look into at some point. Anyway, all tests passed so I'll merge it to master.

Thanks a lot for this fix!

**Pull request merged**
