### PR TITLE
Support Erlang/OTP 21

### PR DESCRIPTION
**Pull request by larshesel**
See #738 for details.

This removes `eper` as a dependency, ignores warnings in `clique`, upgrades `rebar3` to version 3.5.3.

Still a few things to go. See the issue for details.

### CODE REVIEW

**Comment by larshesel** [comment]
NOTE: upgrading to the new rebar3 again breaks loading external plugins: 
```
Can't enable plugin: vmq_allow_all_v5 due to {unknown_module,vmq_allow_all_v5}
```

We need to get to the bottom of this - this happened last time we upgraded rebar3 and we reverted back to fix this. Now we have to figure out what the problem is to be able to support OTP 21.

**Comment by codeadict** [comment]
This is great, was the external plugin compiled with the same Rebar3?

**Comment by larshesel** [comment]
I figured out what the problem was regarding rebar3/plugins. Sometime after rebar3 v 3.3.6 the mode was changed from `interactive` to `embedded`. In the embedded mode it's not possible to autoload modules (and hence plugin loading will fail). So we need to figure out how to stay in `interactive` mode. It seems it's the `CODE_LOADING_MODE` env variable which has to be set to `interactive`, but I haven't figured where to put this in `node_package`, `cuttlefish`/`rebar3_cuttlefish`,`rebar3` and `relx` to make it a default yet.

**Comment by codeadict** [comment]
Seems like one can add `-mode interactive` to the `vm.args`, that will do the trick.

**Comment by larshesel** [comment]
We have cuttlefish autogenerate the app.config and vm.args - I think the trick would be to get cuttlefish to put the correct stuff into the vm.args file... I got it to work if i do `export CODE_LOADING_MODE=interactive` before starting vernemq.

**Comment by codeadict** [comment]
Yep the solution may be to submit a PR to cuttlefish

**Comment by larshesel** [comment]
@dergraf can you bless this?

**Comment by larshesel** [comment]
nevermind, need to fix some test-suites first...

**Pull request merged**
