### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by dergraf**

### CODE REVIEW

**Comment by larshesel** [comment]
LGTM - but strange the tests fails - guess it's not releated ;)

**Comment by larshesel** [comment]
@ioolkos I'd assume you're also on board with this?

**Comment by dergraf** [comment]
Test still fail due to the vmq_diversity script balancer uniformness test

**Comment by ioolkos** [comment]
Sure, I'm on board! :)

**Comment by larshesel** [comment]
@dergraf go ahead and merge this.

**Pull request merged**
