### PR TITLE
Load the observer that contains etop with the release

### PR DESCRIPTION
**Pull request by codeadict**
This is the fix for #661, accompanying Pull request was submitted the `node_package` repository at https://github.com/erlio/node_package/pull/1. Already tested and working great locally.

### CODE REVIEW

**Comment by ioolkos** [comment]
@codeadict thanks!
I was thinking that `etop` could be added independantly, I'll check if that's possible. I guess the full Observer (as a GUI) is not really needed, at least it wasn't included in the packages so far.

**Comment by dergraf** [comment]
etop should be provided as a standalone erl file. we can't include observer due to the WX dependency.

**Comment by codeadict** [comment]
Ah very True, that is why Basho folks used to rip `etop` from OTP and put it in the patches(this case erlio-patches) directory because there is no way to include etop independently.

**Comment by dergraf** [comment]
exactly

**Comment by dergraf** [comment]
remove `vernemq top` ;)

**Comment by dergraf** [comment]
@codeadict would you be fine with removing top altogether?

**Comment by codeadict** [comment]
Sure, I will remove it

**Comment by codeadict** [comment]
I think recon is good enough to discover top processes

**Comment by codeadict** [comment]
And as i mentioned https://github.com/zhongwencool/observer_cli uses recon and is something i can include really easy with no WX dependencies

**Comment by larshesel** [comment]
I'm not sure if we should include that. If I want to insect a node I usually fire up another node where observer is installed/available and connect via observer to the node I want to investigate. Something like observer_cli could be installed as a plugin if needed, I guess. I'm just thinking along the lines that we shouldn't include anything unless we have a good reason to.

**Comment by codeadict** [comment]
Closing this now, the real fix will be made on erlio/node_package#1.

**Pull request closed without merging**
