### PR TITLE
vmq_passwd: fix build on freebsd

### PR DESCRIPTION
**Pull request by iblis17**
See also: #344, #336

### CODE REVIEW

**Comment by larshesel** [comment]
Hi @iblis17 I think this looks good - I'd however like to have all changes needed to compile VerneMQ on freebsd on a single branch so we can test once that it works and that it doesn't affect our builds and package generations for other systems.

I've started a branch over here: https://github.com/larshesel/vernemq/tree/freebsd but it's very incomplete (mostly the work is to get a freebsd-11 system up and running with erlang inside vagrant) and I don't think I'll have too much time the next weeks to move it forward. Let's see.

In any case, let's keep this PR open and include it into the final branch somehow.

**Comment by iblis17** [comment]
Just add some notes.

- [ ] `eleveldb.so` corruption: https://github.com/erlio/vernemq/issues/344#issuecomment-294123113
    - workaround: https://github.com/erlio/vernemq/issues/344#issuecomment-293807893
- [ ] erlio/eleveldb#1

**Comment by iblis17** [comment]
@dergraf I am on a tight schedule this week... I will catch it up soon.

**Comment by iblis17** [comment]
👌

**Pull request merged**
